# DCOS params:
zookeeper: "{{ groups['masters'] | join(':2181,') }}:2181"

# mesos-agent
resources_ports: "{{ over_resources_ports | default('10000-34000') }}"
system_user: "Administrator"

# specific for service run
mesos_workers:
  windows:
    service_name: "mesos-agent"
    homedir: "C:\\dcos"
    bindir: "C:\\dcos\\mesos-binaries"
    workdir: "C:\\dcos\\work"
    imagesdir: "C:\\dcos\\images"
    logdir: "C:\\dcos\\mesos-logs"
    attributes: "os:windows"
    executor: "C:\\dcos\\mesos-binaries\\mesos-agent.exe"

# Packages location
bucket_name: "dcos-win.s3.amazonaws.com"
url_to_mesosbin: "http://{{ bucket_name }}/mesos-binaries.{{ dcos['version'] }}.zip"
