# DCOS params:
dcos_version_specifier: "{{ dcos_version | default('1.13') }}"
zookeeper: "{{ groups['masters'] | join(':2181,') }}:2181"

# mesos-agent specific
mesos_agent_restart_count: 100
mesos_agent_restart_interval: "PT1M" # every 1min
system_user: "Administrator"

# Packages location
bucket_name: "dcos-win.s3.amazonaws.com"
url_to_mesosbin: "http://{{ bucket_name }}/{{ dcos_version_specifier }}/mesos-binaries.zip"
