---
# see man lspci (-d)
nvidia_device_query:
  - vendor: "10de"
    class: "0302"
  - vendor: "10de"
    class: "0300"
vault_repo_baseurl: "http://vault.centos.org/{{ os_release_file['content'] |b64decode | regex_search('\\d+\\.\\d+\\.\\d+') }}/os/$basearch/"
nvidia_repo_rpm: https://developer.download.nvidia.com/compute/cuda/repos/rhel7/x86_64/cuda-repo-rhel7-10.1.168-1.x86_64.rpm

nvidia_repo_baseurl: http://developer.download.nvidia.com/compute/cuda/repos/rhel7/x86_64
nvidia_repo_gpgkey: http://developer.download.nvidia.com/compute/cuda/repos/rhel7/x86_64/7fa2af80.pub

rhel7_vulkan_repo_baseurl: http://mirror.centos.org/centos/7/os/$basearch/
rhel7_vulkan_repo_gpgkey: http://developer.download.nvidia.com/compute/cuda/repos/rhel7/x86_64/7fa2af80.pub
