- name: Windows | Defining DC/OS by using 'version' or, more specifically, 'image_commit'
  set_fact:
     dcos_version_specifier: "{{ dcos['image_commit'] | default(dcos['version']) }}"

# TO DO: remove when Winpanda is able to create Mesos-DNS by its own
- name: Windows | Detect network interface with default_gateway set
  set_fact:
    default_network_interface: "{{ item.connection_name }}"
  when: item.default_gateway is defined and item.default_gateway
  with_items: "{{ ansible_interfaces }}"
  register: default_network_interface_detect
  changed_when: false

- name: Windows | Configures DNS lookup on Windows hosts
  win_dns_client:
    adapter_names: "{{ item.ansible_facts.default_network_interface }}"
    ipv4_addresses: "{{ groups['masters'] | map('extract', hostvars, ['dcos_custom_facts', 'detect_ip']) | list }}"
    log_path: C:\dns_log.txt
  when: item.ansible_facts is defined
  with_items: "{{ default_network_interface_detect.results }}"

# Installation for fresh nodes
- import_tasks: dcos_install.yml
  when: (ansible_local is not defined) or (ansible_local.dcos_installation is not defined) or (ansible_local.dcos_installation['dcos-image-commit'] is not defined)
